spring.application.name=rag-ingestion

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/rag_data
spring.datasource.username=developer
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# AWS S3 Ingestion bucket
amazon.s3.ingestion.bucket=rag-ingestion-904368995177-ap-south-1-an

# Ollama Configuration for LOCAL EMBEDDING MODEL
spring.ai.ollama.embedding.options.model=mxbai-embed-large
spring.ai.ollama.embedding.options.num-ctx=1024
# spring.ai.ollama.base-url=http://127.0.0.1:11434
# spring.ai.model.embedding=ollama
# spring.ai.openai.api-key=""
# spring.ai.openai.embedding.options.dimensions=1024

# Ollama Configuration for CHAT MODEL
spring.ai.ollama.chat.options.model=llama3.2
# spring.ai.model.chat=ollama
# spring.ai.openai.chat.base-url=https://openrouter.ai/api
# spring.ai.openai.chat.api-key=${OPENROUTER_API_KEY}
# spring.ai.openai.chat.options.model=google/gemini-2.5-flash

# Spring AI PgVector Configuration
#spring.ai.vectorstore.pgvector.schema-name=test
spring.ai.vectorstore.pgvector.table-name=rag_chunks
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024